name: border_animator_example
description: Example app for border_animator package.
publish_to: 'none'

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  border_animator:
    path: ../
